version: '2.4'
services:

  mongo:
    build: ./mongo-db/mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ./mongo-data:/data/db:delegated
    ports: 
        - "27017:27017"

  mongo-express:
    build: ./mongo-db/mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on: 
      mongo:
        condition: service_healthy

  backend:
    build: ./node-backend/
    healthcheck:
      test: curl http://127.0.0.1:6200
      timeout: 45s
      interval: 10s
      retries: 10
    command: /app/backend/node_modules/.bin/nodemon /app/backend/index.js
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/app
    environment: 
      - NODE_ENV=development
      - PORT=6200
    depends_on:
      - mongo

  frontend:
    build: ./react-frontend/
    command: bash -c "cd /app/frontend && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/app
    environment: 
      - NODE_ENV=development
    stdin_open: true
    depends_on:
      - backend
# Limpiar el sistema de imagenes y volumenes en dangling
# Imagenes: docker system prune
# Volumes: docker volume rm `docker volume ls -q -f dangling=true`